name: TeamSorter
author: BoxOfDevs Team
authors:
- TheDragonRing
- UltimateMcraft
version: 1.0
description: Ever needed a mult-feature TeamPVP plugin?
api:
- 1.14.2
- 2.0.0
main: TeamSorter\Main
website: http://boxofdevs.ml/software
commands:
    changeteam:
        usage: "/changeteam red|blue [player]"
        description: "Changes yours or another players team"
        permission: teamsorter.change
permissions:
    teamsorter:
        default: false
        children:
            teamsorter.change:
                default: OP