---

# Any items that you want a player to get whenever they join or respawn. Format = "ID:DAMAGE:AMOUNT". Add as many as you want :)

Items:
- "272:0:1"
- "260:0:32"

# The prefix that you want to show with all TeamSorter's broadcasts and messages. Use & or § to colour the text.

Prefix: "§0[§aTeamSorter§0]"

...