---
name: BuildBattle
author:  BoxOfDevs
version: 1.0
api: [2.0.0]
main: BoxOfDevs\BuildBattle\Main
commands: 
   buildbattle:
      description: BuildBattle main command.
      usage: /bb <sub-command> <parameters>
      permission: bb.cmd
      aliases: [bb]
permissions:
  bb.cmd:
    default: true
  bb.op
    default: op
...
