name: onJoinController
author: BoxOfDevs Team
authors:
- Riegert
- TheDragonRing
- KairusDarkSeeker
version: 1.0.0
description: A plugin that allows you to execute set commands when a player joins
api:
- 1.14.2
- 2.0.0
main: onJoinController\Main
load: STARTUP
